### ISSUE TITLE
Hide navigation bar at the bottom.

### ISSUE THREAD

**Issue by wintersandroid** [liuwenchao/aha-table#12]
It would be nice to have an option to hide the navigation pager at the bottom and just show everything (useful for short lists).

:)

**Comment by liuwenchao** [comment]
you can easily achieve this by css, setting tfoot as: display: none. Let me know if you have issue about it.

**Comment by Quelu** [comment]
I can't hide it in CSS, I think It's because i'm using it in an element and my CSS is not in the same shadow DOM.

A "paginate" boolean on <aha-table> that hide the navigation pager and set the pagination to infinite would be perfect :+1:

**Comment by liuwenchao** [comment]
Let me know if you still have issue here.
