### ISSUE TITLE
Needs Material Design or Material Design Lite theme?

### ISSUE THREAD

**Issue by veronicawwashington** [liuwenchao/aha-table#16]
How would you feel about giving <code>aha-table</code> a Material Design Lite theme? [Click here for details](http://www.getmdl.io/components/index.html#tables-section).

**Comment by liuwenchao** [comment]
Sounds great! if you can help, a PR of MDL themed table in index.html will be very welcome.

**Comment by liuwenchao** [comment]
I think we should keep this element as basic as possible and focus on the default behaviour, MDL is great but will not fit in other themes like Bootstrap for example. However, you're welcome to fork and create a mdl-aha-table.
