### ISSUE TITLE
number of results shown per page not updating

### ISSUE THREAD

**Issue by hereiam133** [liuwenchao/aha-table#21]
when you change the number of results to show when viewing the table it does not update the number shown per page until you view a different page.

so if you have a table with 100 results and you are shown 10 per page, and then you click the option to change it to 50 per page, it still says 1 - 10 / 100 (even though there are now 50 per page) until you click to the 2nd page, and then it fixes itself.

**Comment by liuwenchao** [comment]
Fixed by https://github.com/liuwenchao/aha-table/commit/02a9ccb3b54ca37deff921ddc6b049936ce45671
