### ISSUE TITLE
How to implement delete/edit

### ISSUE THREAD

**Issue by dineshnagarit** [liuwenchao/aha-table#22]
I added two paper-fab tag for edit and delete respectively. I am trying to fire an on-tap, on-click event but unable to do that, its simply do not call the function on on-tap while function is already defined.

My backend is in  firebase. I just need to call a function and pass an key as parameter  on on-tap event.

Can I do that by placing  edit/delete in a column for each row? 
Or there anything else simple trick  that I am missing?

**Comment by liuwenchao** [comment]
Can you share the codes so that I can run and debug?
