### ISSUE TITLE
Pretty JSON in table column

### ISSUE THREAD

**Issue by snhne** [liuwenchao/aha-table#24]
Hi. 
I'd like to insert JSON data in table column.

ex)
{
    "foo": "bar"
}

But this is displayed in a line as below.
{"foo": "bar"}

Is there any option for pretty JSON text in table column?
I mean, I'm wondering if aha-table can contain formatted text such a html pre tag.

**Comment by liuwenchao** [comment]
you can try to set type="html", which is provided this PR: https://github.com/liuwenchao/aha-table/pull/14
