### ISSUE TITLE
add support for Polymer 1.2.0

### ISSUE THREAD

**Issue by russ666** [liuwenchao/aha-table#25]
now it generate an error
Uncaught InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': 'value$' is not a valid attribute name.Polymer.Annotations._parseNodeAttributeAnnotation @ polymer.html:183Polymer.Annotations._parseNodeAttributeAnnotations @ polymer.html:162Polymer.Annotations._parseElementAnnotations @ polymer.html:106Polymer.Annotations._parseNodeAnnotations @ polymer.html:28Polymer.Annotations._parseChildNodesAnnotations @ polymer.html:130Polymer.Annotations._parseElementAnnotations @ polymer.html:104Polymer.Annotations._parseNodeAnnotations @ polymer.html:28Polymer.Annotations.parseAnnotations @ polymer.html:24Polymer.Annotations._parseTemplate @ polymer.html:140Polymer.Annotations._parseChildNodesAnnotations @ polymer.html:120Polymer.Annotations._parseElementAnnotations @ polymer.html:104Polymer.Annotations._parseNodeAnnotations @ polymer.html:28Polymer.Annotations._parseChildNodesAnnotations @ polymer.html:130Polymer.Annotations._parseElementAnnotations @ polymer.html:104Polymer.Annotations._parseNodeAnnotations @ polymer.html:28Polymer.Annotations._parseChildNodesAnnotations @ polymer.html:130Polymer.Annotations._parseElementAnnotations @ polymer.html:104Polymer.Annotations._parseNodeAnnotations @ polymer.html:28Polymer.Annotations.parseAnnotations @ polymer.html:24Polymer.Annotations._parseTemplate @ polymer.html:140Polymer.Annotations._parseChildNodesAnnotations @ polymer.html:120Polymer.Annotations._parseElementAnnotations @ polymer.html:104Polymer.Annotations._parseNodeAnnotations @ polymer.html:28Polymer.Annotations._parseChildNodesAnnotations @ polymer.html:130Polymer.Annotations._parseElementAnnotations @ polymer.html:104Polymer.Annotations._parseNodeAnnotations @ polymer.html:28Polymer.Annotations.parseAnnotations @ polymer.html:24Polymer.Annotations._parseTemplate @ polymer.html:140Polymer.Annotations._parseChildNodesAnnotations @ polymer.html:120Polymer.Annotations._parseElementAnnotations @ polymer.html:104Polymer.Annotations._parseNodeAnnotations @ polymer.html:28Polymer.Annotations._parseChildNodesAnnotations @ polymer.html:130Polymer.Annotations._parseElementAnnotations @ polymer.html:104Polymer.Annotations._parseNodeAnnotations @ polymer.html:28Polymer.Annotations._parseChildNodesAnnotations @ polymer.html:130Polymer.Annotations._parseElementAnnotations @ polymer.html:104Polymer.Annotations._parseNodeAnnotations @ polymer.html:28Polymer.Annotations.parseAnnotations @ polymer.html:24Polymer.Base._addFeature._prepAnnotations @ polymer.html:274Polymer.Base._addFeature._registerFeatures @ polymer.html:3364Polymer.Base.registerCallback @ polymer-micro.html:144desugar @ polymer-micro.html:73window.Polymer @ polymer-micro.html:57(anonymous function) @ aha-table.html:380
paper-input-container.html:543 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

**Comment by kuc** [comment]
:+1:

**Comment by hereiam133** [comment]
Same issue here any update??

**Comment by varun-aggarwal** [comment]
Getting the same issue in my project.

**Comment by johanetox** [comment]
So I removed the "$" from this lines L280, L286. L292, L298 and the error stop showing up, after that is  aha-table going to work 100%?
One more question, why the error stopped when in line 201 we have another "value$"?

nice work btw.

**Comment by liuwenchao** [comment]
It won't work by removing $, we will have this issue fixed when Polymer release a new version with the Pull Request linked in this ticket merged.
