### ISSUE TITLE
Sort Integer type data

### ISSUE THREAD

**Issue by gihubtravi** [liuwenchao/aha-table#26]
Hello
Column contains numbers and we want to enable user to sort them as integers.
What is the correct approach is recommended?

Currently they get sorted as string. so breaks for 11, 9, 1 as an example.

**Comment by liuwenchao** [comment]
Make sure the numbers are passed as Number, like this:

```
[
{targetColumn: 2, otherColumn: 'xxx'},
{targetColumn: 9, otherColumn: 'xxx'},
{targetColumn: 11, otherColumn: 'xxx'},
{targetColumn: 1, otherColumn: 'xxx'}
]
```
