### ISSUE TITLE
Server-side pagination support

### ISSUE THREAD

**Issue by pmros** [liuwenchao/aha-table#3]
I'd like aha-table support server-side pagination. I mean something like [DataTables Server-side processing](http://www.datatables.net/manual/server-side). So you get data from server page by page instead every item/row at once. This is very important when you work with big databases.
Thank you for aha-table.

**Comment by liuwenchao** [comment]
Supporting ajax call here will basically add a parallel logic to almost all of the functionalities, which looks too far away from aha-table's main purpose, so I decided to not implement this now. so I'm closing it now, feel free to continue discussion.

You can achieve this feature by maintaining the data of aha-table with your own ajax code, for example:

```javascript
var data = $('aha-table').data;
$.get('count', function(result) {
  data = new Array(result.count);
});
$.get('list?page=1&size=10', function(records) {
  for(i=0; i<10; i++) {
    data[i] = records[i];
  }
});
```

The code above is not tested, just a demonstration on the possible way.
