### ISSUE TITLE
Weird behavior on row checkboxes when selecting/unselecting all - solved for me

### ISSUE THREAD

**Issue by Iskalla** [liuwenchao/aha-table#7]
I found a weird behavior when checking selectall after having selected some of the rows. When playing a bit aroud I ended up having some selected rows (grey highlight on themed table) without their checkboxes checked and come unselected rows with their boxes checked.

I solved this problem for me by changing 
    checked?="{{ row._selected }}"/>
with 
    checked="{{ row._selected }}"/>

on line 226

**Comment by liuwenchao** [comment]
I can't reproduce it here, Do you have a certain way to reproduce this issue? 

OS version, Browser version, any error in developer console?

**Comment by liuwenchao** [comment]
Close it as not reproducible at my side. Let me know if it still not working for you. Thanks!
