### ISSUE TITLE
Port to polymer 0.8

### ISSUE THREAD

**Issue by MetaMemoryT** [liuwenchao/aha-table#8]

**Comment by liuwenchao** [comment]
Thanks, from https://github.com/Polymer/polymer/releases, the latest release is v0.8.0-rc.7. I prefer to move over when it's stable, wdyt?

**Comment by liuwenchao** [comment]
Never mind, after reviewing https://www.polymer-project.org/0.8/, it seems they are encouraging us to port to 0.8 now.

**Comment by MetaMemoryT** [comment]
Yah, vulcanize no longer supports 0.5, so if you want to use the element in production you need to use elements ready for 0.8

**Comment by jonathangrubb** [comment]
Has this been tested at all on Polymer 1.0?

**Comment by liuwenchao** [comment]
Not yet, working on this in branch 2.0.

It didn't go well for polymer 0.8 as template repeater and conditional template were not available in 0.8, which aha-table relies on heavily.
