### ISSUE TITLE
aha-table event for “selectable” checkbox

### ISSUE THREAD

**Issue by troy8** [liuwenchao/aha-table#9]
Hi,
I am trying to implement aha-table using Polymer Js. While creating the table I have kept "selectable" attribute true and as expected I am getting the checkboxes before each row, so, I would like to know is there a way to handle/catch the check/unckeck event of such checkboxes. I am able to handle the cell click event for a cell with "after-td-click" event.

The functionality proposed is when user checks/unchecks the checkbox (and not on click of a cell), then we need to select that particular checked row and refresh a graph for that row and for that I need to have an event to handle this scenario, I feel.

I could not find any any such event for the same.

P.S.  Don't mind I just gone through the aha-table implementation and found out that if an event  after-row-selected (say) is fired in select (data manipulation) function then it will be very helpful.

Thanks for your help in advance...

-- Roy

**Comment by liuwenchao** [comment]
@troy8 please try with v1.1.7 and see if before-select and after-select are good for you.

**Comment by troy8** [comment]
Thank you.. I will check the same...
